site_name: 'illumos'
repo_name: 'illumos/docs'
repo_url: 'https://github.com/illumos/docs'

pages:
  - 'Home': 'index.md'
  - 'About':
    - 'What is illumos?': 'about/index.md'
    - 'Who uses illumos?': 'about/who.md'
    - 'Features': 'about/features.md'
    - 'Leadership': 'about/leadership.md'
    - 'Distributions': 'about/distro.md'
    - 'FAQ': 'about/faq.md'
    - 'Logo': 'about/logo.md'
    - 'History':
      - 'Overview': 'about/history.md'
      - 'Announcement': 'about/announcement.md'
  - 'User Guide':
    - 'Getting Started': 'user-guide/index.md'
    - 'Bug Reporting': 'user-guide/bugs.md'
    - 'Building illumos': 'user-guide/build.md'
    - 'Manuals': 'user-guide/manual.md'
    - 'Debugging': 'user-guide/debug.md'
  - 'Security': 'security/index.md'
  - 'Flag Days': 'flagdays/index.md'
  - 'Contributing':
    - 'Overview': 'contributing/index.md'
    - 'System state': 'contributing/quality.md'
    - 'Quality Death Spiral': 'contributing/qds.md'
  - 'Community':
    - 'Overview': 'community/index.md'
    - 'Mailing Lists': 'community/lists.md'
    - 'Events': 'community/events.md'
    - 'Videos': 'community/videos.md'
  - 'Projects': 'projects/index.md'

theme:
  name: 'material'
  logo: 'images/logo.png'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - markdown_include.include:
      base_path: docs
